# Generated by Django 3.2 on 2022-11-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='subscription',
            field=models.CharField(choices=[('guest', 'Guest'), ('standart', 'Standart'), ('premium', 'Premium')], default='guest', max_length=10, verbose_name='subscription'),
        ),
    ]

